
name: tag image and push to aliacr

on:
  workflow_dispatch:
    inputs:
      pull-image:
        description: 'Image to pull'
        default: 'wordpress:6-php8.1-fpm'
        required: true
      push-image:
        description: 'Image to push'
        default: 'registry.cn-zhangjiakou.aliyuncs.com/baidonghui_cr/wordpress:6-php8.1-fpm'
        required: true
        
# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-zhangjiakou

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    # 1.1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"

    # 1.2 Buid and push image to ACR
    - name: Build and push image to ACR
      run: |
        docker pull ${{ github.event.inputs.pull-image }}
        docker tag  ${{ github.event.inputs.pull-image }}  ${{ github.event.inputs.push-image }}
        docker push ${{ github.event.inputs.push-image }}

